### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by MichaelPaulukonis** [mattfister/wordtools#1]
Oh, wow, offline-wordnet!

Could you add some documentation on what a "reduced version of conceptnet" actually is?

**Comment by mattfister** [comment]
Thanks for the feedback. I updated my [readme.md](https://github.com/mattfister/wordtools/blob/master/README.md) to add some information on conceptnet_reduced and its usage. Let me know what you think.

**Comment by MichaelPaulukonis** [comment]
Lots more info, thanks!

Question - how did you generate the `.json` files?

I plan on playing around with it this week.
Probably translating the python to NodeJS.

I expect more questions to arise with play/use....

**Comment by mattfister** [comment]
I downloaded the flat csvs from [here](http://conceptnet5.media.mit.edu/downloads/current/).  These are massive so it was just a matter of parsing them without running out of memory.

**Comment by MichaelPaulukonis** [comment]
Would you have tools you used to reparse those files into the formats here?

If so, they could be useful for others to build files with the features they want (antonyms, in my case).

**Comment by mattfister** [comment]
Actually - I think I do. It's pretty ugly but the relevant code is in this [previous version](https://github.com/mattfister/twitterbots/blob/master/PyTwitterBots/conceptnet/conceptnet_searcher.py) of my conceptnet_searcher script. The relevant function is [chop_csvs](https://github.com/mattfister/twitterbots/blob/master/PyTwitterBots/conceptnet/conceptnet_searcher.py#L24-L60). It's a real mess though. I think I had to run it on my desktop cause I was running out of memory on my laptop.
